name: Clean up reports

on:
  workflow_dispatch:

  # schedule:
  #   - cron: '30 */4 * * *' # run every 4 hours
  workflow_run:
    workflows: [Report]
    types:
      - completed

concurrency:
  group: cleanup

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  update-stats:
    name: "Clean up reports"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clean up reports
        run: |
          echo "::group::Clean up reports"
          node ./bin/clean-reports.js
          echo "::endgroup::"
