name: Remove test reports from closed or merged pull requests
on:
  schedule:
    - cron: "30 7 * * 0"
  workflow_dispatch:
  push:
    branches:
      - update/delete-reports-from-closed-merged-prs

jobs:
  remove-reports:
    name: Remove reports
    runs-on: ubuntu-20.04
    env:
      PR_LIST_PATH: ${{ github.workspace }}/tmp/pr_list.txt
      FILTERED_LIST_PATH: ${{ github.workspace }}/tmp/filtered_list.txt
    steps:
      - name: Create dirs
        run: |
          mkdir -p repo
          mkdir -p tmp

      - uses: actions/checkout@v3
        with:
          # MYTODO switch to trunk prior to merge
          ref: update/delete-reports-from-closed-merged-prs
          path: repo
          token: ${{ secrets.REPORTS_TOKEN }}

      - name: List all PR numbers in repo
        working-directory: repo/docs/pr
        run: |
          ls > ${{ env.PR_LIST_PATH }}
          echo "List of PR numbers currently in the repo:"
          cat ${{ env.PR_LIST_PATH }}

      - name: Filter closed or merged PR's
        working-directory: repo/.github/workflows/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
        run: |
          bash filter-list.sh
          echo "List of PR's that are already merged or closed:"
          cat $FILTERED_LIST_PATH

      - name: Run command for deleting reports from closed/merged PR's
        working-directory: repo/.github/workflows/scripts
        run: bash delete-closed-merged-pr-reports.sh

      - name: Push changes to repo
        if: ${{ false }}
        working-directory: repo
        env:
          GITHUB_USER: ${{ secrets.REPORTS_USER }}
          GITHUB_EMAIL: ${{ secrets.REPORTS_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
          BOT_COMMIT_MESSAGE: Cleanup reports from closed or merged pull requests
        run: |
          git config user.name $GITHUB_USER
          git config user.email $GITHUB_EMAIL
          git add .
          git commit -m "$BOT_COMMIT_MESSAGE"
          git pull --rebase
          git push "https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"

