name: Publish test report on PR merge
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
      artifact:
        required: true
      pr_number:
        required: true
      test_type:
        description: e2e or api
        required: true
        type: choice
        options:
          - api
          - e2e
concurrency:
  group: ${{ github.workflow }}-${{ inputs.pr_number }}
  cancel-in-progress: true
permissions: {}

jobs:
  publish:
    name: Publish Allure report
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Create dirs
        run: |
          mkdir -p repo
          mkdir -p artifact

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: repo
          token: ${{ secrets.REPORTS_TOKEN }}

      - name: Install allure-commandline package
        run: npm install -g allure-commandline

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download artifact
        env:
          SOURCE: ${{ secrets.S3_BUCKET_URL }}/artifacts/${{ inputs.run_id }}/${{ inputs.artifact }}
          DESTINATION: artifact
        run: aws s3 cp $SOURCE $DESTINATION --recursive

      - name: Set report title
        working-directory: repo/.github/workflows/scripts
        env:
          REPORT_TITLE: ${{ inputs.test_type }} Tests on trunk after merging PR ${{ inputs.pr_number }}
          INDEX_HTML_PATH: ${{ github.workspace }}/artifact/allure-report/index.html
          SUMMARY_JSON_PATH: ${{ github.workspace }}/artifact/allure-report/widgets/summary.json
        run: node change-report-title.js

      - name: Upload test reports to S3 bucket
        env:
          SOURCE: artifact/allure-report
          DESTINATION: ${{ secrets.S3_BUCKET_URL }}/public/pr-merge/${{ inputs.pr_number }}/${{ inputs.test_type }}
        run: aws s3 sync $SOURCE $DESTINATION --delete

      - name: Add index.md file
        working-directory: repo
        env:
          INDEX_MD_DIR: docs/pr-merge/${{ inputs.pr_number }}/${{ inputs.test_type }}
        run: |
          mkdir -p $INDEX_MD_DIR
          echo "---" > $INDEX_MD_DIR/index.md
          echo "layout: redirect" >> $INDEX_MD_DIR/index.md
          echo "redirect_to: ${{ secrets.S3_WEB_ENDPOINT }}/public/pr-merge/${{ inputs.pr_number }}/${{ inputs.test_type }}/index.html" >> $INDEX_MD_DIR/index.md
          echo "---" >> $INDEX_MD_DIR/index.md

      - name: Create PR and merge
        working-directory: repo/.github/workflows/scripts
        env:
          GITHUB_USER: ${{ secrets.REPORTS_USER }}
          GITHUB_EMAIL: ${{ secrets.REPORTS_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
          BOT_COMMIT_MESSAGE: 'Add: ${{ inputs.test_type }} test against trunk after merging PR ${{ inputs.pr_number }}'
          BRANCH_NAME: 'add/${{ inputs.test_type }}-report-on-pr-merge-${{ inputs.pr_number }}-runid-${{ inputs.run_id }}'
          RUN_ID: ${{ inputs.run_id }}
        run: bash merge-changes-to-trunk.sh

      - name: Delete artifact from bucket
        run: aws s3 rm ${{ secrets.S3_BUCKET_URL }}/artifacts/${{ inputs.run_id }}/${{ inputs.artifact }} --recursive
