name: Publish Daily smoke test report
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Daily smoke test workflow run ID.
        required: true
      api_artifact:
        description: API test report artifact.
        required: true
      commit_message:
        description: Latest commit message in woocommerce/woocommerce:trunk at the time the Daily smoke test worflow was triggered.
        required: true

jobs:
  publish_test_report:
    name: Publish test report
    runs-on: ubuntu-20.04
    env:
      RUN_ID: ${{ github.event.inputs.run_id }}
      API_ARTIFACT: ${{ github.event.inputs.api_artifact }}
      DOWNLOAD_PATH: ${{ github.workspace }}/download
      REPO_PATH: ${{ github.workspace }}/repo
      GITHUB_TOKEN: ${{ github.token }}
      COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
    steps:
      - name: Create dirs
        run: |
          mkdir -p $DOWNLOAD_PATH
          mkdir -p $REPO_PATH

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_PATH }}
          token: ${{ secrets.REPORTS_TOKEN }}

      - name: Install allure-commandline package
        run: npm install -g allure-commandline

      - name: Download API test report artifact
        working-directory: ${{ env.REPO_PATH }}/.github/workflows/scripts
        env:
          ARTIFACT_NAME: ${{ env.API_ARTIFACT }}
        run: bash download-report.sh

      - name: Regenerate 
        if: ${{ false }}
        run: ${{ env.REPO_PATH }}/.github/workflows/scripts/regenerate-report.sh

      - name: Push changes to repo
        if: ${{ false }}
        env:
          GH_USER: ${{ secrets.REPORTS_USER }}
          GH_EMAIL: ${{ secrets.REPORTS_EMAIL }}
          GH_TOKEN: ${{ secrets.REPORTS_TOKEN }}
        run: ${{ env.REPO_PATH }}/.github/workflows/scripts/push-changes.sh

      - name: Prepare Slack message
        if: ${{ false }}
        id: slack_message
        working-directory: ${{ env.REPO_PATH }}/.github/workflows/scripts
        run: |
          SLACK_MESSAGE=$(COMMIT_MESSAGE="$COMMIT_MESSAGE" node prepare-slack-message-daily.js)
          echo "::set-output name=slack_message::$SLACK_MESSAGE"

      - name: Post test report to Slack channel
        if: ${{ false }}
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.E2E_SLACK_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID_DAILY }}
          payload: ${{ steps.slack_message.outputs.slack_message }}
