name: Publish Daily smoke test report
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Daily smoke test workflow run ID.
        required: true
      api_artifact:
        description: API test report artifact.
        required: true
      e2e_artifact:
        description: E2E test report artifact.
      commit_message:
        description: Latest commit message in woocommerce/woocommerce:trunk at the time the Daily smoke test worflow was triggered.
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_test_report:
    name: Publish test report
    runs-on: ubuntu-20.04
    env:
      RUN_ID: ${{ github.event.inputs.run_id }}
      API_ARTIFACT: ${{ github.event.inputs.api_artifact }}
      E2E_ARTIFACT: ${{ github.event.inputs.e2e_artifact }}
      COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
    steps:
      - name: Create dirs
        run: |
          mkdir -p download/api
          mkdir -p download/e2e
          mkdir -p repo

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: repo
          token: ${{ secrets.REPORTS_TOKEN }}

      - name: Install allure-commandline package
        run: npm install -g allure-commandline

      # ####################
      # API Test Report
      # ####################
      - name: Download API test report artifact
        working-directory: repo/.github/workflows/scripts
        env:
          ARTIFACT_NAME: ${{ env.API_ARTIFACT }}
          DOWNLOAD_PATH: ${{ github.workspace }}/download/api
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
        run: bash download-report.sh

      - name: Regenerate and combine API test reports
        working-directory: repo/.github/workflows/scripts
        env:
          REPO_ALLURE_REPORT_PATH: ${{ github.workspace }}/repo/docs/daily/api/allure-report
          REPO_ALLURE_RESULTS_PATH: ${{ github.workspace }}/repo/docs/daily/api/allure-results
          DOWNLOAD_ALLURE_REPORT_PATH: ${{ github.workspace }}/download/api/allure-report
          DOWNLOAD_ALLURE_RESULTS_PATH: ${{ github.workspace }}/download/api/allure-results
        run: bash regenerate-combine-reports.sh

      - name: Customize API test report title
        working-directory: repo/.github/workflows/scripts
        env:
          INDEX_HTML_PATH: ${{ github.workspace }}/repo/docs/daily/api/allure-report/index.html
          SUMMARY_JSON_PATH: ${{ github.workspace }}/repo/docs/daily/api/allure-report/widgets/summary.json
          REPORT_TITLE: Daily API test report - ${{ env.COMMIT_MESSAGE }}
        run: node change-report-title.js

      # ####################
      # E2E Test Report
      # ####################
      - name: Download E2E test report artifact
        working-directory: repo/.github/workflows/scripts
        env:
          ARTIFACT_NAME: ${{ env.E2E_ARTIFACT }}
          DOWNLOAD_PATH: ${{ github.workspace }}/download/e2e
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
        run: bash download-report.sh

      - name: Regenerate and combine E2E test reports
        working-directory: repo/.github/workflows/scripts
        env:
          REPO_ALLURE_REPORT_PATH: ${{ github.workspace }}/repo/docs/daily/e2e/allure-report
          REPO_ALLURE_RESULTS_PATH: ${{ github.workspace }}/repo/docs/daily/e2e/allure-results
          DOWNLOAD_ALLURE_REPORT_PATH: ${{ github.workspace }}/download/e2e/allure-report
          DOWNLOAD_ALLURE_RESULTS_PATH: ${{ github.workspace }}/download/e2e/allure-results
        run: bash regenerate-combine-reports.sh

      - name: Customize E2E test report title
        working-directory: repo/.github/workflows/scripts
        env:
          INDEX_HTML_PATH: ${{ github.workspace }}/repo/docs/daily/e2e/allure-report/index.html
          SUMMARY_JSON_PATH: ${{ github.workspace }}/repo/docs/daily/e2e/allure-report/widgets/summary.json
          REPORT_TITLE: Daily E2E test report - ${{ env.COMMIT_MESSAGE }}
        run: node change-report-title.js

      - name: Push changes to repo
        if: contains(${{ env.GITHUB_REF_NAME }}, 'trunk')
        working-directory: repo/.github/workflows/scripts
        env:
          GITHUB_USER: ${{ secrets.REPORTS_USER }}
          GITHUB_EMAIL: ${{ secrets.REPORTS_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
          BOT_COMMIT_MESSAGE: Add daily test report
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          bash push-changes-to-repo.sh

      - name: Prepare Slack message
        id: prepare_slack_message
        working-directory: repo/.github/workflows/scripts
        run: |
          mkdir -p $GITHUB_WORKSPACE/slack
          SLACK_MESSAGE=$(COMMIT_MESSAGE="$COMMIT_MESSAGE" RUN_ID=$RUN_ID node prepare-slack-message-daily.js)
          echo "$SLACK_MESSAGE" > $GITHUB_WORKSPACE/slack/slack-message.json
          cat $GITHUB_WORKSPACE/slack/slack-message.json

      - name: Post test report to Slack channel
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.E2E_SLACK_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID_DAILY }}
          payload-file-path: ${{ github.workspace }}/slack/slack-message.json
