name: Publish Daily smoke test report
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Daily smoke test workflow run ID.
        required: true
      api_artifact:
        description: API test report artifact.
        required: true
      commit_message:
        description: Latest commit message in woocommerce/woocommerce:trunk at the time the Daily smoke test worflow was triggered.
        required: true

jobs:
  publish_test_report:
    name: Publish test report
    runs-on: ubuntu-20.04
    env:
      RUN_ID: ${{ github.event.inputs.run_id }}
      API_ARTIFACT: ${{ github.event.inputs.api_artifact }}
      COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
    steps:
      - name: Create dirs
        run: |
          mkdir -p download/api
          mkdir -p repo

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: repo
          token: ${{ secrets.REPORTS_TOKEN }}

      - name: Install allure-commandline package
        run: npm install -g allure-commandline

      - name: Download API test report artifact
        working-directory: repo/.github/workflows/scripts
        env:
          ARTIFACT_NAME: ${{ env.API_ARTIFACT }}
          DOWNLOAD_PATH: ${{ github.workspace }}/download/api
        run: bash download-report.sh

      - name: Regenerate and combine reports
        working-directory: repo/.github/workflows/scripts
        env:
          REPO_ALLURE_REPORT_PATH: ${{ github.workspace }}/repo/docs/daily/api/allure-report
          REPO_ALLURE_RESULTS_PATH: ${{ github.workspace }}/repo/docs/daily/api/allure-results
          DOWNLOAD_ALLURE_REPORT_PATH: ${{ github.workspace }}/download/api/allure-report
          DOWNLOAD_ALLURE_RESULTS_PATH: ${{ github.workspace }}/download/api/allure-results
        run: bash regenerate-combine-reports.sh

      - name: Archive API test report
        uses: actions/upload-artifact@v3
        with:
          name: daily-smoke-test-report
          path: ${{ github.workspace }}/repo/docs/daily
          retention-days: 5

      - name: Push changes to repo
        if: ${{ false }}
        env:
          GH_USER: ${{ secrets.REPORTS_USER }}
          GH_EMAIL: ${{ secrets.REPORTS_EMAIL }}
          GH_TOKEN: ${{ secrets.REPORTS_TOKEN }}
        run: repo/.github/workflows/scripts/push-changes.sh

      - name: Prepare Slack message
        if: ${{ false }}
        id: slack_message
        working-directory: repo/.github/workflows/scripts
        run: |
          SLACK_MESSAGE=$(COMMIT_MESSAGE="$COMMIT_MESSAGE" node prepare-slack-message-daily.js)
          echo "::set-output name=slack_message::$SLACK_MESSAGE"

      - name: Post test report to Slack channel
        if: ${{ false }}
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.E2E_SLACK_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID_DAILY }}
          payload: ${{ steps.slack_message.outputs.slack_message }}
