name: Publish test report
on:
  workflow_dispatch:
    inputs:
      test_workflow:
        description: Type of workflow that triggered report generation.
        required: true
        type: choice
        options:
          - daily
          - pr
          - release
      test_type:
        description: Type of test that ran.
        required: true
        type: choice
        options:
          - e2e
          - api
      run_id:
        description: Workflow run ID containing the artifact to be downloaded.
        required: true
      artifact_name:
        description: Name of artifact to be downloaded.
        required: true
      woo_repo:
        description: Repository that triggered this workflow.
        default: woocommerce/woocommerce
      pr_number:
        description: If test_workflow is 'pr', this is the WooCommerce PR that generated the test report.
      commit_sha:
        description: Commit SHA of pull request that triggered this workflow.

jobs:
  publish_test_report:
    name: Publish test report
    runs-on: ubuntu-20.04
    env:
      TEST_WORKFLOW: ${{ github.event.inputs.test_workflow }}
      TEST_TYPE: ${{ github.event.inputs.test_type }}
      RUN_ID: ${{ github.event.inputs.run_id }}
      ARTIFACT_NAME: ${{ github.event.inputs.artifact_name }}
      PR_NUMBER: ${{ github.event.inputs.pr_number }}
      COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
      WOO_REPO: ${{ github.event.inputs.woo_repo }}
      DOWNLOAD_PATH: ${{ github.workspace }}/download
      REPO_PATH: ${{ github.workspace }}/repo
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Validate PR number
        if: ${{ github.event.inputs.test_workflow == 'pr' }}
        run: gh pr view $PR_NUMBER --repo $WOO_REPO >> /dev/null

      - name: Create dirs
        run: |
          mkdir -p $DOWNLOAD_PATH
          mkdir -p $REPO_PATH

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_PATH }}
          token: ${{ secrets.REPORTS_TOKEN }}

      - name: Get commit message
        if: ${{ github.event.inputs.test_workflow == 'pr' }}
        working-directory: ${{ env.REPO_PATH }}/.github/workflows/scripts
        run: bash get-commit-message.sh

      - name: Install allure-commandline package
        run: npm install -g allure-commandline

      - name: Download test report
        run: ${{ env.REPO_PATH }}/.github/workflows/scripts/download-report.sh

      - name: Regenerate report
        run: ${{ env.REPO_PATH }}/.github/workflows/scripts/regenerate-report.sh

      - name: Push changes to repo
        env:
          GH_USER: ${{ secrets.REPORTS_USER }}
          GH_EMAIL: ${{ secrets.REPORTS_EMAIL }}
          GH_TOKEN: ${{ secrets.REPORTS_TOKEN }}
        run: ${{ env.REPO_PATH }}/.github/workflows/scripts/push-changes.sh

      - name: Add comment to PR
        if: ${{ github.event.inputs.test_workflow == 'pr' }}
        working-directory: ${{ env.REPO_PATH }}/.github/workflows/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
        run: bash add-pr-comment.sh
