name: Publish test report on trunk merge
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
      artifact:
        required: true
      pr_number:
        required: true
      test_type:
        description: e2e or api
        required: true
        type: choice
        options:
          - api
          - e2e
concurrency:
  group: ${{ github.workflow }}-${{ inputs.pr_number }}

jobs:
  publish:
    name: Publish report on trunk merge
    runs-on: ubuntu-20.04
    steps:
      - name: Get commit message
        id: commit-message
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          commit_message=$(gh api repos/woocommerce/woocommerce/commits/${{ inputs.pr_number }} --jq ".commit.message")
          echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_OUTPUT

      - name: Print commit message
        env:
          COMMIT_MESSAGE: ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}
        run: echo "$COMMIT_MESSAGE"
