name: Publish Daily smoke test report
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Daily smoke test workflow run ID.
        required: true
      api_artifact:
        description: API test report artifact.
        required: true
      e2e_artifact:
        description: E2E test report artifact.
      commit_message:
        description: Latest commit message in woocommerce/woocommerce:trunk at the time the Daily smoke test worflow was triggered.
        required: true
      s3_root:
        required: true
        default: test
        type: choice
        options:
          - public
          - test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_daily_test_reports:
    name: Publish daily smoke test reports
    runs-on: ubuntu-20.04
    env:
      RUN_ID: ${{ github.event.inputs.run_id }}
      API_ARTIFACT: ${{ github.event.inputs.api_artifact }}
      E2E_ARTIFACT: ${{ github.event.inputs.e2e_artifact }}
      COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
      S3_ROOT: ${{ github.event.inputs.s3_root }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Create dirs
        run: |
          mkdir -p repo
          mkdir -p artifacts/api
          mkdir -p artifacts/e2e
          mkdir -p s3/api
          mkdir -p s3/e2e
          mkdir -p output/api
          mkdir -p output/e2e

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: repo
          token: ${{ secrets.REPORTS_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Install allure-commandline package
        run: npm install -g allure-commandline

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # ####################
      # API Test Report
      # ####################
      - name: Download API test report artifact
        env:
          ARTIFACT_NAME: ${{ env.API_ARTIFACT }}
          DOWNLOAD_PATH: ${{ github.workspace }}/artifacts/api
        working-directory: repo/.github/workflows/scripts
        run: bash download-report.sh

      - name: Download existing API test report from S3 bucket
        working-directory: repo/.github/workflows/scripts
        id: api-s3-download
        env:
          SOURCE: ${{ secrets.S3_BUCKET_URL }}/${{ env.S3_ROOT }}/daily/api
          DESTINATION: ${{ github.workspace }}/s3/api
        run: bash s3-download-report.sh

      - name: Prepare first API report for upload
        if: fromJSON( steps.api-s3-download.outputs.HAS_PREVIOUS_REPORT ) != true
        run: cp -r artifacts/api/allure-report/* output/api

      - name: Regenerate API test report with history
        if: fromJSON( steps.api-s3-download.outputs.HAS_PREVIOUS_REPORT )
        working-directory: repo/.github/workflows/scripts
        env:
          OLD_ALLURE_REPORT_PATH: ${{ github.workspace }}/s3/api
          NEW_ALLURE_RESULTS_PATH: ${{ github.workspace }}/artifacts/api/allure-results
          OUTPUT_PATH: ${{ github.workspace }}/output/api
        run: bash regenerate-report-v2.sh

      - name: Set API report title
        working-directory: repo/.github/workflows/scripts
        env:
          REPORT_TITLE: 'Daily API Smoke Test Report - ${{ env.COMMIT_MESSAGE }}'
          INDEX_HTML_PATH: ${{ github.workspace }}/output/api/index.html
          SUMMARY_JSON_PATH: ${{ github.workspace }}/output/api/widgets/summary.json
        run: node change-report-title.js

      # ####################
      # E2E Test Report
      # ####################
      - name: Download E2E test report artifact
        env:
          ARTIFACT_NAME: ${{ env.E2E_ARTIFACT }}
          DOWNLOAD_PATH: ${{ github.workspace }}/artifacts/e2e
        working-directory: repo/.github/workflows/scripts
        run: bash download-report.sh

      - name: Download existing E2E test report from S3 bucket
        working-directory: repo/.github/workflows/scripts
        id: e2e-s3-download
        env:
          SOURCE: ${{ secrets.S3_BUCKET_URL }}/${{ env.S3_ROOT }}/daily/e2e
          DESTINATION: ${{ github.workspace }}/s3/e2e
        run: bash s3-download-report.sh

      - name: Prepare first E2E report for upload
        if: fromJSON( steps.e2e-s3-download.outputs.HAS_PREVIOUS_REPORT ) != true
        run: cp -r artifacts/e2e/allure-report/* output/e2e

      - name: Regenerate E2E test report with history
        if: fromJSON( steps.e2e-s3-download.outputs.HAS_PREVIOUS_REPORT )
        working-directory: repo/.github/workflows/scripts
        env:
          OLD_ALLURE_REPORT_PATH: ${{ github.workspace }}/s3/e2e
          NEW_ALLURE_RESULTS_PATH: ${{ github.workspace }}/artifacts/e2e/allure-results
          OUTPUT_PATH: ${{ github.workspace }}/output/e2e
        run: bash regenerate-report-v2.sh

      - name: Set E2E report title
        working-directory: repo/.github/workflows/scripts
        env:
          REPORT_TITLE: 'Daily E2E Smoke Test Report - ${{ env.COMMIT_MESSAGE }}'
          INDEX_HTML_PATH: ${{ github.workspace }}/output/e2e/index.html
          SUMMARY_JSON_PATH: ${{ github.workspace }}/output/e2e/widgets/summary.json
        run: node change-report-title.js

      - name: Upload test reports to S3 bucket
        env:
          API_DESTINATION: ${{ secrets.S3_BUCKET_URL }}/${{ env.S3_ROOT }}/daily/api
          E2E_DESTINATION: ${{ secrets.S3_BUCKET_URL }}/${{ env.S3_ROOT }}/daily/e2e
        run: |
          aws s3 sync output/api $API_DESTINATION --delete
          aws s3 sync output/e2e $E2E_DESTINATION --delete

      - name: Prepare Slack message
        id: prepare_slack_message
        working-directory: repo/.github/workflows/scripts
        run: |
          mkdir -p $GITHUB_WORKSPACE/slack
          SLACK_MESSAGE=$(COMMIT_MESSAGE="$COMMIT_MESSAGE" \
            RUN_ID=$RUN_ID \
            API_SUMMARY_JSON=${{ github.workspace }}/output/api/widgets/summary.json \
            E2E_SUMMARY_JSON=${{ github.workspace }}/output/e2e/widgets/summary.json \
            node prepare-slack-message-daily.js)
          echo "$SLACK_MESSAGE" > $GITHUB_WORKSPACE/slack/slack-message.json
          cat $GITHUB_WORKSPACE/slack/slack-message.json

      - name: Post test report to Slack channel
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.E2E_SLACK_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID_DAILY }}
          payload-file-path: ${{ github.workspace }}/slack/slack-message.json
